{{- if .Values.freezerApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openstack-freezer.fullname" . }}-api
  labels:
    {{- include "openstack-freezer.labels" . | nindent 4 }}
    component: api
spec:
  type: {{ .Values.freezerApi.service.type }}
  ports:
    - port: {{ .Values.freezerApi.service.port }}
      targetPort: {{ .Values.freezerApi.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "openstack-freezer.selectorLabels" . | nindent 4 }}
    component: api
{{- end }}
