apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openstack-freezer.fullname" . }}-config
  labels:
    {{- include "openstack-freezer.labels" . | nindent 4 }}
data:
  freezer-api.conf: |
    [DEFAULT]
    bind_host = 0.0.0.0
    bind_port = 9090
    log_file = /var/log/freezer/freezer-api.log
    log_dir = /var/log/freezer

    [database]
    connection = mysql+pymysql://{{ .Values.database.username }}:$(FREEZER_DB_PASSWORD)@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}

    [keystone_authtoken]
    www_authenticate_uri = {{ .Values.keystone.authUrl }}
    auth_url = {{ .Values.keystone.authUrl }}
    auth_type = password
    project_domain_name = {{ .Values.keystone.service.projectDomainName }}
    user_domain_name = {{ .Values.keystone.service.userDomainName }}
    project_name = {{ .Values.keystone.service.projectName }}
    username = {{ .Values.keystone.service.username }}
    password = $(FREEZER_KEYSTONE_PASSWORD)
    region_name = {{ .Values.keystone.region }}

    [oslo_messaging_rabbit]
    rabbit_host = {{ .Values.messaging.host }}
    rabbit_port = {{ .Values.messaging.port }}
    rabbit_userid = {{ .Values.messaging.username }}
    rabbit_password = $(FREEZER_RABBIT_PASSWORD)
    rabbit_virtual_host = {{ .Values.messaging.vhost }}

    [storage]
    driver = {{ .Values.storage.driver }}

    [swift]
    auth_url = {{ .Values.storage.swift.authUrl }}
    auth_version = 3
    username = {{ .Values.storage.swift.username }}
    password = $(FREEZER_SWIFT_PASSWORD)
    project_name = {{ .Values.storage.swift.projectName }}
    project_domain_name = {{ .Values.storage.swift.projectDomainName }}
    user_domain_name = {{ .Values.storage.swift.userDomainName }}
    container = {{ .Values.storage.swift.container }}

  freezer-scheduler.conf: |
    [DEFAULT]
    log_file = /var/log/freezer/freezer-scheduler.log
    log_dir = /var/log/freezer

    [api]
    url = http://{{ include "openstack-freezer.fullname" . }}-api:{{ .Values.freezerApi.service.port }}

    [database]
    connection = mysql+pymysql://{{ .Values.database.username }}:$(FREEZER_DB_PASSWORD)@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}

    [keystone_authtoken]
    www_authenticate_uri = {{ .Values.keystone.authUrl }}
    auth_url = {{ .Values.keystone.authUrl }}
    auth_type = password
    project_domain_name = {{ .Values.keystone.service.projectDomainName }}
    user_domain_name = {{ .Values.keystone.service.userDomainName }}
    project_name = {{ .Values.keystone.service.projectName }}
    username = {{ .Values.keystone.service.username }}
    password = $(FREEZER_KEYSTONE_PASSWORD)
    region_name = {{ .Values.keystone.region }}

    [oslo_messaging_rabbit]
    rabbit_host = {{ .Values.messaging.host }}
    rabbit_port = {{ .Values.messaging.port }}
    rabbit_userid = {{ .Values.messaging.username }}
    rabbit_password = $(FREEZER_RABBIT_PASSWORD)
    rabbit_virtual_host = {{ .Values.messaging.vhost }}
