{{- if .Values.freezerApi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openstack-freezer.fullname" . }}-api
  labels:
    {{- include "openstack-freezer.labels" . | nindent 4 }}
    component: api
spec:
  replicas: {{ .Values.freezerApi.replicaCount }}
  selector:
    matchLabels:
      {{- include "openstack-freezer.selectorLabels" . | nindent 6 }}
      component: api
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.freezerApi.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "openstack-freezer.selectorLabels" . | nindent 8 }}
        component: api
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openstack-freezer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.freezerApi.podSecurityContext | nindent 8 }}
      containers:
        - name: freezer-api
          securityContext:
            {{- toYaml .Values.freezerApi.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.freezerApi.image.repository }}:{{ .Values.freezerApi.image.tag }}"
          imagePullPolicy: {{ .Values.freezerApi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v2
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v2
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.freezerApi.resources | nindent 12 }}
          env:
            - name: FREEZER_API_CONFIG_FILE
              value: /etc/freezer/freezer-api.conf
          volumeMounts:
            - name: config
              mountPath: /etc/freezer
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "openstack-freezer.fullname" . }}-config
      {{- with .Values.freezerApi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.freezerApi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.freezerApi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
