# Kubernetes Secret to store sensitive configuration data like passwords.
# This should be managed securely in a production environment.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freezer.fullname" . }}-secrets
  labels:
    {{- include "freezer.labels" . | nindent 4 }}
type: Opaque
data:
  # Database password
  freezer-db-password: {{ .Values.database.password | b64enc | quote }}
  # RabbitMQ password
  rabbitmq-password: {{ .Values.rabbitmq.password | b64enc | quote }}
  # Keystone admin password (for bootstrapping service user)
  keystone-admin-password: {{ .Values.keystone.adminPassword | b64enc | quote }}
  # Freezer service user password
  freezer-service-password: {{ .Values.serviceUser.password | b64enc | quote }}
